# Generated by Django 4.1 on 2023-06-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='topic',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='floor',
        ),
    ]
